Task1
sergey-berezin/s02170680 pull request #1
Opened 2020-10-03 19:57 UTC by NikkyTheChamp

2020-10-03 20:45 UTC, NikkyTheChamp reviewed
Наверное зря я это сделал :)

2020-10-06 16:27 UTC, NikkyTheChamp commented
вроде все исправил

2020-10-11 19:29 UTC, sergey-berezin requested changes

2020-10-11 19:29 UTC, sergey-berezin commented on ImagePredConsole/Program.cs
> +            Console.Write(model.ErrorMsg);
А если ошибки нет? Лучше в случае ошибки бросать исключение в компоненте и использовать try/catch в пользовательском коде.

2020-10-11 19:29 UTC, sergey-berezin commented on ImagePredConsole/output.txt
> +156...\ModelLib\Samples\7 - Copy - Copy - Copy.png 0: 4.758783E-16; 1: 1.1090573E-06; 2: 3.8000085E-08; 3: 7.604928E-08; 4: 1.5474625E-17; 5: 9.735935E-16; 6: 2.0854873E-20; 7: 0.99999875; 8: 8.88349
Это файл не нужен в репозитории.

2020-10-12 09:00 UTC, sergey-berezin approved these changes

2020-10-12 09:00 UTC, merged